'use client';

import { Bell, CheckCheck, CircleAlert, Mail, Settings2 } from 'lucide-react';
import { useState } from 'react';
import { AppShell } from '../components/app-shell';

const initialNotifications = [{ title: 'Sensor expires tomorrow', text: 'VS-2048-AX assigned to Mara Ellison needs attention.', time: '12 min ago', priority: 'Critical', unread: true }, { title: 'New sensor assigned', text: 'Aisha Morgan assigned VS-2280-LP to the active inventory.', time: '34 min ago', priority: 'Normal', unread: true }, { title: 'Expiration report ready', text: 'Your April expiration report is ready to download.', time: '1 hr ago', priority: 'Normal', unread: false }, { title: 'Sensor expiration digest', text: '17 sensors are entering their expiration window this week.', time: 'Yesterday', priority: 'High', unread: false }];

export default function NotificationsPage() { const [notifications, setNotifications] = useState(initialNotifications); const unread = notifications.filter((item) => item.unread).length; return <AppShell><div className="page-content"><section className="page-heading"><div><p className="eyebrow">Inbox</p><h1>Notifications</h1><p className="heading-copy">Stay ahead of assignments, expiration windows, and security events.</p></div><div className="heading-actions"><button className="secondary-button" onClick={() => setNotifications(notifications.map((item) => ({ ...item, unread: false })))}><CheckCheck size={16} /> Mark all read</button><button className="icon-button"><Settings2 size={18} /></button></div></section><div className="notification-summary"><Bell size={19} /><strong>{unread} unread notifications</strong><span>Across in-app and email channels</span></div><section className="panel notification-panel">{notifications.map((item, index) => <article className={`notification-row ${item.unread ? 'notification-unread' : ''}`} key={item.title}><div className={`notification-icon notification-${item.priority.toLowerCase()}`}>{item.priority === 'Critical' ? <CircleAlert size={17} /> : <Mail size={17} />}</div><div className="notification-copy"><strong>{item.title}</strong><span>{item.text}</span><time>{item.time}</time></div><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority}</span><button className="row-link" onClick={() => setNotifications(notifications.map((current, currentIndex) => currentIndex === index ? { ...current, unread: false } : current))}>{item.unread ? 'Mark read' : 'Read'}</button></article>)}</section></div></AppShell>; }
