'use client';

import { CheckCheck, CircleAlert, Mail, RefreshCw, Settings2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { AppShell } from '../components/app-shell';
import { apiFetch } from '../../lib/api';

type Notification = { _id: string; title: string; message: string; priority: string; status: string; createdAt?: string };
export default function NotificationsPage() { const [notifications, setNotifications] = useState<Notification[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = async () => { setLoading(true); try { setNotifications(await apiFetch<Notification[]>('/notifications')); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load notifications'); } finally { setLoading(false); } }; useEffect(() => { void load(); }, []); const markAll = async () => { await apiFetch('/notifications/read-all', { method: 'PATCH' }); await load(); }; const markRead = async (id: string) => { await apiFetch(`/notifications/${id}/read`, { method: 'PATCH' }); await load(); }; return <AppShell><div className="page-content"><section className="page-heading"><div><p className="eyebrow">Inbox</p><h1>Notifications</h1><p className="heading-copy">Live alerts and messages for your account.</p></div><div className="heading-actions"><button className="secondary-button" onClick={() => void markAll()}><CheckCheck size={16} /> Mark all read</button><button className="icon-button"><Settings2 size={18} /></button></div></section>{loading && <div className="data-loading"><RefreshCw size={18} className="spin" />Loading notifications...</div>}{error && <div className="data-error"><span>{error}</span></div>}{!loading && !error && <section className="panel notification-panel">{notifications.length === 0 ? <div className="empty-panel"><h2>No notifications</h2><p>New operational alerts will appear here.</p></div> : notifications.map((item) => <article className={`notification-row ${item.status === 'UNREAD' ? 'notification-unread' : ''}`} key={item._id}><div className={`notification-icon notification-${item.priority.toLowerCase()}`}>{item.priority === 'CRITICAL' ? <CircleAlert size={17} /> : <Mail size={17} />}</div><div className="notification-copy"><strong>{item.title}</strong><span>{item.message}</span><time>{item.createdAt ? new Date(item.createdAt).toLocaleString() : 'Unknown'}</time></div><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority}</span>{item.status === 'UNREAD' && <button className="row-link" onClick={() => void markRead(item._id)}>Mark read</button>}</article>)}</section>}</div></AppShell>; }
