'use client';

import { Plus, RefreshCw, ShieldCheck, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { AppShell } from '../components/app-shell';
import { apiFetch } from '../../lib/api';

type Employee = { _id: string; firstName: string; lastName: string; email: string; role: string; status: string };
export default function TeamPage() { const [members, setMembers] = useState<Employee[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { void apiFetch<Employee[]>('/employees').then(setMembers).catch((caught) => setError(caught instanceof Error ? caught.message : 'Unable to load team')).finally(() => setLoading(false)); }, []); return <AppShell><div className="page-content"><section className="page-heading"><div><p className="eyebrow">People & access</p><h1>Team</h1><p className="heading-copy">Live workspace members and their API-enforced roles.</p></div><button className="primary-button"><Plus size={17} /> Invite member</button></section><section className="role-banner"><ShieldCheck size={19} /><div><strong>Role-based access is enabled</strong><span>Permissions are enforced by the API for every request.</span></div></section>{loading && <div className="data-loading"><RefreshCw size={18} className="spin" />Loading team...</div>}{error && <div className="data-error"><span>{error}</span></div>}{!loading && !error && <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Workspace members</p><h2>Team directory</h2></div><span className="result-count">{members.length} loaded</span></div>{members.length === 0 ? <div className="empty-panel"><h2>No team members</h2><p>Invite a member after their Supabase identity is created.</p></div> : <div className="member-list">{members.map((member) => <div className="member-row" key={member._id}><div className="member-avatar">{member.firstName[0]}{member.lastName[0]}</div><div className="member-copy"><strong>{member.firstName} {member.lastName}</strong><span>{member.email}</span></div><span className="role-label">{member.role}</span><span className={`status status-${member.status.toLowerCase()}`}><i />{member.status}</span><button className="icon-button" aria-label={`Manage ${member.firstName}`}><UserRound size={17} /></button></div>)}</div>}</section>}</div></AppShell>; }
