'use client';

import { ClipboardList, Download, Search } from 'lucide-react';
import { useState } from 'react';
import { AppShell } from '../components/app-shell';

const events = [{ actor: 'Aisha Morgan', action: 'SENSOR_ASSIGNED', entity: 'VS-2280-LP', time: 'Aug 11, 2026 09:42', source: 'Dashboard' }, { actor: 'Jordan Tate', action: 'CUSTOMER_UPDATED', entity: 'Mara Ellison', time: 'Aug 11, 2026 09:18', source: 'Customer record' }, { actor: 'Olivia Chen', action: 'REPORT_EXPORTED', entity: 'Expiration report', time: 'Aug 11, 2026 08:30', source: 'Reports' }, { actor: 'Ravi Khatri', action: 'SENSOR_CREATED', entity: 'OX-8830-TR', time: 'Aug 10, 2026 16:12', source: 'Inventory' }, { actor: 'Olivia Chen', action: 'SETTINGS_CHANGED', entity: 'Notification preferences', time: 'Aug 10, 2026 14:04', source: 'Settings' }];

export default function AuditPage() { const [query, setQuery] = useState(''); const filtered = events.filter((event) => `${event.actor} ${event.action} ${event.entity}`.toLowerCase().includes(query.toLowerCase())); return <AppShell><div className="page-content"><section className="page-heading"><div><p className="eyebrow">Immutable history</p><h1>Audit log</h1><p className="heading-copy">Every important workspace action is recorded and cannot be edited.</p></div><button className="secondary-button"><Download size={16} /> Export log</button></section><section className="toolbar"><div className="search-field"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search actor, action, or entity" /></div><span className="result-count">{filtered.length} events</span></section><section className="panel"><div className="audit-intro"><ClipboardList size={19} /><span>Showing the most recent activity for <strong>Northstar Care</strong></span></div><div className="table-wrap"><table className="rich-table"><thead><tr><th>Actor</th><th>Action</th><th>Entity</th><th>Timestamp</th><th>Source</th></tr></thead><tbody>{filtered.map((event) => <tr key={`${event.time}-${event.action}`}><td><strong>{event.actor}</strong></td><td><span className="audit-action">{event.action}</span></td><td>{event.entity}</td><td className="muted-cell">{event.time}</td><td className="muted-cell">{event.source}</td></tr>)}</tbody></table></div></section></div></AppShell>; }
