'use client';

import { ArrowLeft, Edit3, RefreshCw, UserRound } from 'lucide-react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { AppShell } from '../../components/app-shell';
import { apiFetch } from '../../../lib/api';

type Customer = { _id: string; customerNumber: string; firstName: string; lastName: string; email?: string; phone?: string; address?: string; status: string };
export default function CustomerDetailPage() { const params = useParams<{ id: string }>(); const [customer, setCustomer] = useState<Customer>(); const [error, setError] = useState(''); useEffect(() => { if (!params.id) return; void apiFetch<Customer>(`/customers/${params.id}`).then(setCustomer).catch((caught) => setError(caught instanceof Error ? caught.message : 'Unable to load customer')); }, [params.id]); return <AppShell><div className="page-content narrow-content"><Link className="back-link" href="/customers"><ArrowLeft size={15} /> Back to customers</Link>{!customer && !error && <div className="data-loading"><RefreshCw size={18} className="spin" />Loading customer...</div>}{error && <div className="data-error"><span>{error}</span></div>}{customer && <><section className="detail-heading"><div className="detail-identity"><div className="detail-avatar"><UserRound size={23} /></div><div><p className="eyebrow">Customer profile</p><h1>{customer.firstName} {customer.lastName}</h1><span>{customer.customerNumber} · {customer.status}</span></div></div><button className="secondary-button"><Edit3 size={15} /> Edit profile</button></section><div className="detail-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Profile information</p><h2>Contact details</h2></div></div><dl className="detail-list"><div><dt>Email</dt><dd>{customer.email ?? 'Not provided'}</dd></div><div><dt>Phone</dt><dd>{customer.phone ?? 'Not provided'}</dd></div><div><dt>Address</dt><dd>{customer.address ?? 'Not provided'}</dd></div><div><dt>Status</dt><dd>{customer.status}</dd></div></dl></section><section className="panel empty-panel"><h2>Sensor history</h2><p>Assignment history will appear here when the customer has linked sensors.</p><Link className="ghost-button" href="/sensors">Open sensor inventory →</Link></section></div></>}</div></AppShell>; }
