'use client';

import { ArrowLeft, Edit3, MoreHorizontal, UserRound } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import { AppShell } from '../../components/app-shell';

export default function CustomerDetailPage() {
  const [tab, setTab] = useState('Overview');
  const customerId = 'CUS-10482';
  return <AppShell><div className="page-content narrow-content"><Link className="back-link" href="/customers"><ArrowLeft size={15} /> Back to customers</Link><section className="detail-heading"><div className="detail-identity"><div className="detail-avatar"><UserRound size={23} /></div><div><p className="eyebrow">Customer profile</p><h1>Mara Ellison</h1><span>{customerId} · Active since January 2025</span></div></div><div className="heading-actions"><button className="secondary-button"><Edit3 size={15} /> Edit profile</button><button className="icon-button" aria-label="More customer actions"><MoreHorizontal size={19} /></button></div></section><div className="detail-tabs">{['Overview', 'Sensor history', 'Documents', 'Activity'].map((item) => <button key={item} className={tab === item ? 'detail-tab detail-tab-active' : 'detail-tab'} onClick={() => setTab(item)}>{item}</button>)}</div>{tab === 'Overview' ? <><div className="detail-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Profile information</p><h2>Contact details</h2></div></div><dl className="detail-list"><div><dt>Email</dt><dd>mara.ellison@example.com</dd></div><div><dt>Phone</dt><dd>+1 (555) 014-8820</dd></div><div><dt>Address</dt><dd>18 Meadow Lane, Portland, ME 04101</dd></div><div><dt>Emergency contact</dt><dd>Devon Ellison · +1 (555) 014-8821</dd></div></dl></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Current allocation</p><h2>Assigned sensors</h2></div><Link className="ghost-button" href="/sensors">Manage <span>→</span></Link></div><div className="assigned-device"><div className="device-symbol">VS</div><div><strong>VS-2048-AX</strong><span>VitalSense Pro · Expiring tomorrow</span></div><span className="status status-warning"><i />Expiring</span></div><div className="assigned-device"><div className="device-symbol device-blue">OX</div><div><strong>OX-8830-TR</strong><span>OxiTrack Mini · Expires Sep 02</span></div><span className="status status-healthy"><i />Active</span></div></section></div><section className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">Recent changes</p><h2>Customer activity</h2></div><Link className="ghost-button" href="/audit">View audit <span>→</span></Link></div><div className="activity-list"><div className="activity-row"><div className="activity-avatar activity-green">JT</div><div className="activity-copy"><strong>Jordan Tate</strong><span>updated phone number</span></div><time>34 min ago</time></div><div className="activity-row"><div className="activity-avatar activity-blue">AM</div><div className="activity-copy"><strong>Aisha Morgan</strong><span>assigned VS-2048-AX</span></div><time>Jan 14, 2025</time></div></div></section></> : <section className="panel empty-panel"><h2>{tab}</h2><p>This customer workspace view is ready for the connected API data source.</p></section>}</div></AppShell>;
}
